import type { CategoryKey } from '../domain/categories';
import type { Filter } from './state';

/**
 * Everything the reducer can change. Entity ids are pre-generated by the
 * caller with uid() so the reducer stays a pure (state, command) function.
 */
export interface MissionInput {
  id: string;
  title: string;
  category: CategoryKey;
  x: number | null;
  y: number | null;
  // Form values arrive as strings; legacy parses with parseInt(...) || 100
  respect: number | string;
  items: { id: string; text: string }[];
}

export type AppCommand =
  | { type: 'toggleItem'; missionId: string; itemId: string }
  | { type: 'createMission'; mission: MissionInput }
  | { type: 'deleteMission'; missionId: string }
  | { type: 'selectMission'; missionId: string | null }
  | { type: 'setFilter'; filter: Filter }
  | { type: 'toggleSound' };
